### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the source of truth for this Elixir
library and leverage on latest features of ExDoc.

### CODE REVIEW

**Comment by kianmeng** [comment]
@mroth Any updates on this?

**Comment by mroth** [comment]
@kianmeng sorry for the delay, I somehow missed this before!

This looks good, appreciate it.  I haven’t used Elixir myself currently for a while — will anything need to be done to push a new release following this for HexDocs to pick it up, or will merging to master suffice?

**Comment by kianmeng** [comment]
@mroth I see. Merging to master and publish to Hexdocs.pm should be sufficient enough. Thanks.

**Comment by kianmeng** [comment]
:tada: :tada: :tada: :tada: :tada:

**Pull request merged**
