### PR TITLE
update .travis.yml for more recent elixir and otp versions

### PR DESCRIPTION
**Pull request by jeffweiss**

### CODE REVIEW

**Comment by mroth** [comment]
Appreciate this! :heart:

To avoid totally hammering Travis CI's servers, I'd like to get the number of test permutations down.  Since OTP versions are matrixed with Elixir versions, currently this ends up requiring 30 different VM runs to do the integration tests (resulting in a 8-9 minute test wait due to queuing).

On Elixir versions, it's probably sufficient to just test the most recent from 1.2.x, 1.1.x, 1.0.x (not sure if Travis has a good shorthand for this).

I'd make that change first, and then we can see in the Travis buildlog where the breakage distinctions are in regards of OTP versions.

(Yeah, I know that's a departure from what I was doing previously with the 1.0.x series, so apologies.)

**Comment by jeffweiss** [comment]
@mroth significantly smaller test matrix. Also excluding elixir 1.2 from attempting to test on erlang 17.x since elixir 1.2 explicitly requires erlang 18+.

**Comment by mroth** [comment]
Looks great!  Thanks so much.  I'm going to update a few files and whatnot but will bump to a new version and release on Hex

**Comment by jeffweiss** [comment]
💜

**Pull request merged**
